{% set version = "0.10.0" %}

package:
  name: pylbm
  version: {{ version }}

source:
  git_url: https://github.com/pylbm/pylbm.git
  git_rev: {{ version }}

build:
  number: 0
  script: "{{PYTHON}} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - hatch
  run:
    - python >=3.6
    - numpy
    - numpy-stl
    - matplotlib-base
    - sympy >=1.3
    - cython
    - h5py
    - mpi4py
    - colorlog
    - colorama
    - cerberus
    - jinja2

test:
  requires:
    - mpich  # [not win]
  imports:
    - pylbm

about:
  home: http://pylbm.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A flexible Python package for lattice Boltzmann method

extra:
  recipe-maintainers:
    - gouarin
