{% set version = "0.4.1" %}

# mpi must be defined for conda-smithy lint
{% if not mpi %}
# conda-smithy misbehaves if mpi is unset
{% set mpi = 'mpich' %}
{% endif %}

package:
  name: pylbm
  version: {{ version }}

source:
  git_url: https://github.com/pylbm/pylbm.git
  git_rev: {{ version }}

build:
  number: 0
  script: "{{PYTHON}} setup.py install --single-version-externally-managed --record record.txt"
  noarch: python

requirements:
  host:
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - numpy
    - matplotlib
    - sympy >=1.1.1,<1.2
    - cython
    - h5py
    - {{ mpi }}
    - mpi4py
    - colorlog
    - colorama
    - cerberus
    - jinja2

test:
  imports:
    - pylbm

about:
  home: http://pylbm.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A flexible Python package for lattice Boltzmann method

extra:
  recipe-maintainers:
    - gouarin
