travis:
  secure:
    BINSTAR_TOKEN: mbmDbDVyzgHFwjv0Ve46K126LlEDMY+ld8t5hYtz41It5h/aEBCQZvHnVgMiH7senmIWEnHfuObmhxSsOioQBOADvyYHBwwKUhLp59oTzS57yDS+DnBXwvCEJBq2tl+HWzc1hYdr+q/S9AATGW3nSOIzGUOMbjpf9LYYZFPO5bNyD49/REiDM2eMzISUMkc0FTZYCdWtRXbDuMBGa0vrqn2hV22qJ+bHg5ljhiV4HJzF2nuTjUqBsVjV+uCzCHULSn3abJ4eiNJU1ZQLrWL74TvrILqMgYlN1D1L0HftAROvjm717b9iZGT57GQsNgc1M5FSXOH/meLWyQNqdELnAJXekGTLNWlLay8nFufOOUos3iffCrwXZ854aSu0g/vk3PUZXVBBcCqgeqNKev73jYroT9PS71BO2CRjII6aC7Mkj7Zpz8qUTMuABdDsujMws4/YYXk4ruyXMZU74R5ukxLBAulwDOTj4iUqjwggWaexLHY2CSXWH7ohKJLGHGdJq/N3MnAPoJe8J1TYc6qeLUCRHrJGVQF1dD+gJUqY2yEiYjrv33KkvQV03KhZBrKY6ldMjYV7usF0QdlKNp367TH8qUufjEXLS8hWcIe1nBqtmOXE7ixi5I3s7Am7/g/LGMpMdIyD2hHE/HKz7sPcz+CrB25oQJidfGjlynSAaAo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
